jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - continue-on-error: true
      run: cd web-vue && npm i && npm run build
    - continue-on-error: true
      name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        cache: maven
        distribution: temurin
        java-version: '8'
    - continue-on-error: true
      name: Build with Maven
      run: mvn -B package
    strategy:
      matrix:
        node-version:
        - 16.x
name: build
on:
  repository_dispatch:
    types: trigger-ga___build.yml
